### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by Winthan** [IgniteUI/crypto-portfolio-app#38]
Instead of clicking on refresh, How can It refresh itself every 15 sec?

**Comment by zdrawku** [comment]
You can try using `interval() Observable`. Just keep in ming that `interval() Observable` will need a 'startWith' to give you an initial event.

```
private readonly autoRefresh$ = interval(15000).pipe(startWith(0));
private readonly refreshToken$ = new BehaviorSubject(undefined);

private readonly task$ = combineLatest(this.autoRefresh$, this.refreshToken$)
	.pipe(
	  switchMap(() => this.http.get('/api/tasks/foo'))
	);
```

**Comment by Winthan** [comment]
I am getting an interval undefined error when I add the code in block-grid-components.ts 

vendor.js:57516 ERROR Error: Uncaught (in promise): ReferenceError: interval is not defined
ReferenceError: interval is not defined

**Comment by Winthan** [comment]
on block-grid.component.ts:
below line 48 -
 ``` 
  setTimeout(() => {
      this.refreshGrid();
    }, 100);

```
to 

  ```
setTimeout(() => {
      this.refreshGrid();
    }, 100);

 setInterval(this.refreshGrid(), 15000);
```
when I set up with setInterval, it doesn't refreshGrid.  How can I make my Grid to pull data service every 15 sec?  Thanks!

**Comment by zdrawku** [comment]
hey again, this was example code, if you want to add such logic in the crypto app, you can simply use `rxjs interval` that creates an Observable that emits a sequence of integers spaced by a given time interval.

[This ](https://github.com/IgniteUI/crypto-portfolio-app/pull/39/files#diff-38060f3bdf19a715fb84669ef8ef75c7R30)is the PR that is showing how to do so:

```
interval(15000).startWith(0).subscribe(() => {
      this.dataService.getData().subscribe(res => {
        this.remoteData = res;
      });
    });
```

**Comment by Winthan** [comment]
Thanks, that works.
