### ISSUE TITLE
Save Filter Setting automatically 

### ISSUE THREAD

**Issue by Winthan** [IgniteUI/crypto-portfolio-app#40]
When users have a bunch of filter settings.  The setting of filters must be saved automatically in cookies. Even after Page is reloaded, the setting of filter will stay intact with the app until cookies expired or reset.  That will prevent users at setting with filters again if the page is reloaded on the web browser.

**Comment by Winthan** [comment]
that will be great if we can save custom filter set as a workspace according to their profile, so they can load nicely their set.

**Comment by zdrawku** [comment]
Hey @Winthan, this is a great suggestion. We have a section in [our documentation that covers](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence) how to manually persist different states, although it doesn't include implementation for custom filters or excel style filtering. This is why we've added this functionality [as a feature request](https://github.com/IgniteUI/igniteui-angular/issues/5460) in our product repository.
